development:
  secret_key_base: key
  publishable_key: pk_test_51MVj4IC7Jfkko8zkGuVjkdPEHtJQZxSMRLGLCIzWmTz9oYgS9qOaZtklic52ULYfOCNPyU4lv5hsHKICkcvagaq400Ybv4JSdk
  secret_key: sk_test_51MVj4IC7Jfkko8zk6EzmVJnYACCGhrsm4QQ0VZLABljHTgdO1xRMkde6x5rJBdnvb9yNGozytZjaNYDWZ7NG7iHw00o5iWqJCB